sudo: required

language: generic

services:
  - docker

before_install:
  - echo "creating image with dockerfile"
  - docker build -t dudfhd705/travistest -f Dockerfile .

scripts:
  - echo "test success"
  - docker run -e CI=true -p 3001:3001 dudfhd705/travistest npm run build -- --coverage
